# Generated by Django 4.1.3 on 2023-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_aws_query_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws_query',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
