# Generated by Django 4.1.3 on 2023-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_alter_aws_query_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_id', models.IntegerField()),
                ('packet_type', models.CharField(max_length=255)),
            ],
        ),
    ]
