# Generated by Django 4.1.3 on 2023-01-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_alter_packet_info_packet_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather_forecast_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
