# Generated by Django 4.1.3 on 2023-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_weather_forecast_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='avalanche_grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True)),
                ('grid_id', models.CharField(max_length=4)),
            ],
        ),
    ]
