# Generated by Django 4.1.3 on 2023-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_avalanche_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_grid',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
