# Generated by Django 4.1.3 on 2022-12-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pointers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('point_type', models.CharField(choices=[('marker', 'marker'), ('polygon', 'polygon')], max_length=255)),
            ],
        ),
    ]
