# Generated by Django 4.1.3 on 2022-12-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointers',
            options={'verbose_name': 'pointer'},
        ),
        migrations.AddField(
            model_name='pointers',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pointers',
            name='point_type',
            field=models.CharField(choices=[('marker', 'marker'), ('polygon', 'polygon'), ('label', 'label')], max_length=255),
        ),
    ]
