# Generated by Django 4.1.3 on 2022-12-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_pointers_options_pointers_create_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointers',
            unique_together={('longitude', 'latitude')},
        ),
    ]
