# Generated by Django 4.1.3 on 2023-02-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_pointers_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointers',
            name='filee',
            field=models.FileField(blank=True, null=True, upload_to='filess'),
        ),
        migrations.AddField(
            model_name='pointers',
            name='station_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointers',
            name='terminal_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
