# Generated by Django 4.1.3 on 2023-02-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_pointers_filee_pointers_station_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointers',
            name='point_type',
        ),
    ]
