# Generated by Django 4.1.3 on 2022-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_on', models.DateTimeField(auto_now_add=True)),
                ('sms_type', models.BooleanField(default=False)),
                ('sms_message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
