# Generated by Django 4.1.3 on 2022-12-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sms_message',
            new_name='message_description',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sms_on',
            new_name='message_on',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sms_type',
            new_name='message_type',
        ),
    ]
