# Generated by Django 4.1.3 on 2022-12-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_sms_message_message_message_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_description',
            field=models.JSONField(),
        ),
    ]
