# Generated by Django 4.1.3 on 2023-01-03 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0003_alter_message_message_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avalanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_on', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.IntegerField()),
                ('message_str', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(max_length=255)),
                ('sequence_num', models.IntegerField()),
                ('packet_id', models.CharField(max_length=255)),
                ('grid_id', models.CharField(max_length=4)),
                ('fragment_id', models.IntegerField()),
                ('no_fragment', models.IntegerField()),
                ('update_on', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=6, null=True)),
                ('axis_id', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
