# Generated by Django 4.1.3 on 2023-01-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_avalanche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
