# Generated by Django 4.1.3 on 2023-02-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avalanche',
        ),
    ]
