# Generated by Django 4.1.3 on 2023-01-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ws_sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_on', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255)),
                ('packet_id', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
