# Generated by Django 4.1.3 on 2023-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ws_sessions',
            name='packet_id',
            field=models.IntegerField(),
        ),
    ]
