# Generated by Django 4.1.3 on 2023-01-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0002_alter_ws_sessions_packet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ws_sessions',
            name='logout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ws_sessions',
            name='logout_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ws_sessions',
            name='packet_id',
            field=models.CharField(max_length=100),
        ),
    ]
