# Generated by Django 4.1.3 on 2023-01-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0004_hourly_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourly_data',
            options={'verbose_name': 'Hour Data'},
        ),
    ]
