# Generated by Django 4.1.3 on 2023-01-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0006_alter_hourly_data_aws_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourly_data',
            options={},
        ),
    ]
