# Generated by Django 4.1.3 on 2023-01-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0008_rename_hourly_data_hour_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Running_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_run', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
