# Generated by Django 4.1.3 on 2023-01-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0009_running_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='running_details',
            name='is_run',
            field=models.BooleanField(default=False),
        ),
    ]
