# Generated by Django 4.1.3 on 2023-01-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0010_alter_running_details_is_run'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hour_message',
            new_name='Receive_message',
        ),
    ]
