# Generated by Django 4.1.3 on 2023-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0011_rename_hour_message_receive_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive_message',
            name='data',
            field=models.CharField(max_length=117),
        ),
    ]
