# Generated by Django 4.1.3 on 2023-01-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0012_alter_receive_message_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=117)),
                ('terminal_id', models.CharField(max_length=5)),
                ('query_code', models.CharField(max_length=2)),
                ('data_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
            ],
        ),
    ]
