# Generated by Django 4.1.3 on 2023-01-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0014_alter_query_message_data_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websocket_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('is_connect', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
