# Generated by Django 4.1.3 on 2023-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0016_remove_websocket_status_is_connect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receive_message',
            old_name='transmission_mode',
            new_name='sensor_code',
        ),
        migrations.AlterField(
            model_name='receive_message',
            name='data',
            field=models.CharField(max_length=255),
        ),
    ]
