# Generated by Django 4.1.3 on 2023-01-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0017_rename_transmission_mode_receive_message_sensor_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Send_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=117)),
                ('terminal_id', models.CharField(max_length=5)),
                ('query_code', models.CharField(max_length=2)),
                ('message_date', models.CharField(max_length=6)),
                ('end_time', models.TimeField()),
                ('current_date', models.CharField(max_length=6)),
                ('current_time', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Query_message',
        ),
    ]
