# Generated by Django 4.1.3 on 2023-01-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0018_query_send_message_delete_query_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_send_message',
            name='end_time',
            field=models.CharField(max_length=4),
        ),
    ]
