# Generated by Django 4.1.3 on 2023-01-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0019_alter_query_send_message_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_send_message',
            name='sequence_num',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
