# Generated by Django 4.1.3 on 2023-01-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0021_alter_query_send_message_sequence_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_send_message',
            name='send_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query_send_message',
            name='sequence_num',
            field=models.IntegerField(default=40, unique=True),
        ),
    ]
