# Generated by Django 4.1.3 on 2023-01-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0022_query_send_message_send_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_send_message',
            name='sequence_num',
            field=models.IntegerField(),
        ),
    ]
