# Generated by Django 4.1.3 on 2023-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0023_alter_query_send_message_sequence_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_send_message',
            name='ack',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ws_sessions',
            name='log_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
