# Generated by Django 4.1.3 on 2023-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0025_receive_message_ack'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='csv_data')),
            ],
        ),
    ]
