# Generated by Django 4.1.3 on 2023-01-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0027_command_message_reboot_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command_message',
            old_name='send_data',
            new_name='json_data',
        ),
        migrations.RenameField(
            model_name='reboot_message',
            old_name='packet',
            new_name='json_data',
        ),
    ]
