# Generated by Django 4.1.3 on 2023-01-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0029_command_message_send_by_query_send_message_send_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive_message',
            name='ack',
        ),
        migrations.AddField(
            model_name='receive_message',
            name='packet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
