# Generated by Django 4.1.3 on 2023-01-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0030_remove_receive_message_ack_receive_message_packet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive_message',
            name='packet_id',
        ),
    ]
