# Generated by Django 4.1.3 on 2023-01-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0031_remove_receive_message_packet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive_message',
            name='packet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
