# Generated by Django 4.1.3 on 2023-01-30 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wss_handler', '0033_remove_message_backup_file_message_backup_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reboot_message',
            old_name='received_on',
            new_name='send_on',
        ),
        migrations.CreateModel(
            name='Weather_Forecast_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_on', models.DateTimeField(auto_now=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('sequence_num', models.IntegerField()),
                ('ack', models.BooleanField(blank=True, null=True)),
                ('start_date', models.CharField(max_length=6)),
                ('grid_id', models.CharField(max_length=4)),
                ('num_of_forecast_day', models.CharField(max_length=2)),
                ('forecast_area', models.CharField(max_length=3)),
                ('day_1', models.CharField(max_length=2)),
                ('day_2', models.CharField(max_length=2)),
                ('day_3', models.CharField(max_length=2)),
                ('day_4', models.CharField(max_length=2)),
                ('day_5', models.CharField(max_length=2)),
                ('day_6', models.CharField(max_length=2)),
                ('send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
