# Generated by Django 4.1.3 on 2023-01-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0035_rename_received_on_query_send_message_send_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_forecast_message',
            name='packet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
