# Generated by Django 4.1.3 on 2023-02-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0038_avalanche_message_one_avalanche_message_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id10',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id11',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id12',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id13',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id14',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id15',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id2',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id3',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id4',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id5',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id6',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id7',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id8',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_id9',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code10',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code11',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code12',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code13',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code14',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code15',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code2',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code3',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code4',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code5',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code6',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code7',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code8',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_code9',
            field=models.CharField(default='00', max_length=1),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='message_type',
            field=models.IntegerField(default=91),
        ),
        migrations.AlterField(
            model_name='avalanche_message_two',
            name='message_type',
            field=models.IntegerField(default=98),
        ),
    ]
